on: [push, pull_request]
name: Build
jobs:
  docker:
    strategy:
      matrix:
        go-version: [1.16.x]
        goos: [linux]
        goarch: [amd64]
    runs-on: ubuntu-latest
    steps:
    - name: Install go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run build
      run: make all
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
    - name: Packaging
      run: tar -zcvf paddleflow-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz output/
    - name: Uploading assets
      uses: actions/upload-artifact@v3
      with:
        name: paddleflow-${{ matrix.goos }}-${{ matrix.goarch }}
        path: paddleflow-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz

    - name: Get branch name
      id: branch-name
      with:
        strip_tag_prefix: true
      env:
        strip_tag_prefix: true
      uses: tj-actions/branch-names@v6

    - name: echo branch
      run: |
        echo "is_default=${{ steps.branch-name.outputs.is_default }}"
        echo "is_tag=${{ steps.branch-name.outputs.is_tag }}"
        echo "tag=${{ steps.branch-name.outputs.tag }}"

    - uses: nelonoel/branch-name@v1.0.1
    - run: |
        echo ${BRANCH_NAME}
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

    - name: get build-image-enabled, version-fragment and current-version
      run: |
        current_branch=${{ env.BRANCH_NAME }}
        event_name=${{ github.event_name }}
        build_image_enabled=false
        echo "current_branch is [$current_branch]"
        if [[ $current_branch =~ ^(release|dev|master|main).* ]];then
          echo "current_branch is [$current_branch]"
          if [[ $event_name == 'push' ]]; then
          echo "event_name is [$event_name]"
          build_image_enabled=true
          fi
        fi

        echo "build_image_enabled is [$build_image_enabled]"
        echo "build_image_enabled=$build_image_enabled" >> $GITHUB_ENV

        echo "version_fragment=alpha" >> $GITHUB_ENV
        if [[ $current_branch =~ ^release.* ]]; then
          echo "version_fragment=rc" >> $GITHUB_ENV

          cur_version=${current_branch#*release}
          cur_version=${cur_version#*/}
          cur_version=${cur_version#*-}
          echo "cur_version is [$cur_version]"
          echo "cur_version=$cur_version" >> $GITHUB_ENV
        fi

        if [ !${{ steps.branch-name.outputs.is_tag }} ]; then
          echo "current branch without tag"
          echo "cur_version=null" >> $GITHUB_ENV
        else
          echo "cur_version is [$steps.branch-name.outputs.tag]"
          echo "cur_version=$steps.branch-name.outputs.tag" >> $GITHUB_ENV
        fi


    - name: Bump release version
      if: env.cur_version!=0 && env.build_image_enabled=='true'
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: ${{ env.cur_version }}
        version-fragment: ${{ env.version_fragment }}

    - if: ${{ env.cur_version!='null' && env.build_image_enabled=='true' }}
      name: print next-version
      run: echo ${{ steps.bump_version.outputs.next-version }}


    - name: Set Image Tag Name, only dev and release
      if: env.build_image_enabled=='true'
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        echo "tagname=null" >> $GITHUB_ENV
        current_branch=${{ env.BRANCH_NAME }}
        base_repo=zzc932/db-crud-api
        arch=${{ matrix.goarch }}
        if [[ !($arch =~ amd.*) ]]; then
          base_repo=$base_repo-$arch
        fi

        if [ !${{ steps.branch-name.outputs.is_tag }} ]; then
          echo "current branch $current_branch without tag"
          if [ ${{ env.version_fragment }} == 'alpha' ]; then
            echo "tagname=$base_repo:latest"
            echo "tagname=$base_repo:latest" >> $GITHUB_ENV
          fi

          if [[ $current_branch =~ ^release.* ]]; then
            echo "tagname=$base_repo:$current_branch"
            echo "tagname=$base_repo:$current_branch" >> $GITHUB_ENV
          fi

        else
          echo "tagname=$base_repo:$current_branch,$base_repo:${{ steps.bump_version.outputs.next-version }}"
          echo "tagname=$base_repo:$current_branch,$base_repo:${{ steps.bump_version.outputs.next-version }}" >> $GITHUB_ENV
        fi

    - name: Login to DockerHub
      if: env.tagname!='null' && env.build_image_enabled=='true'
      uses: docker/login-action@v2
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      if: env.tagname!='null' && env.build_image_enabled=='true'
      uses: docker/build-push-action@v3
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      with:
        context: .
        file: ./installer/Dockerfile
        platforms: ${{ matrix.goarch }}
        push: true
        tags: ${{ env.tagname }}
