on:
  release:
    types: [published, created]
  push:
    branches:
      - master
      - 'releases/**'
name: image_build
jobs:
  docker:
    strategy:
      matrix:
        go-version: [1.17.x]
        goos: [linux]
        goarch: [amd64]
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: GITHUB_REF
        run: echo $GITHUB_REF

      - name: Get $EVENT_CONTEXT
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

      - name: Get branch name
        id: branch-name
        with:
          strip_tag_prefix: true
        env:
          strip_tag_prefix: true
        uses: tj-actions/branch-names@v6

      - name: echo branch
        run: |
          echo "base_ref_branch=${{ steps.branch-name.base_ref_branch }}"
          echo "current_branch=${{ steps.branch-name.current_branch }}"
          echo "ref_branch=${{ steps.branch-name.ref_branch }}"
          echo "tag=${{ steps.branch-name.tag }}"

      - name: Get Image Tag Name
        run: |
          if [ ${{ steps.branch-name.outputs.is_tag }} ]; then
            echo "tagname=${{ steps.branch-name.current_branch }}-latest,${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            echo "tagname=${{ steps.branch-name.current_branch }}-latest" >> $GITHUB_ENV
          fi

      - name: print Image Tag Name
        run: |
          echo ${{ env.tagname }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: ${{ env.tagname != '' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./installer/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.tagname }}

      - name: Build and push2
        if: ${{ env.tagname == '' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./installer/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.tagname }}
