on:
  push:
    branches:
      - master
      - 'releases/**'
name: image_build
jobs:
  strategy:
    matrix:
      go-version: [1.17.x]
      goos: [linux]
      goarch:
        - amd64
        - arm64
  runs-on: ubuntu-latest
  steps:
    - name: Install go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run build
      run: make all
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
    - name: Packaging
      run: tar -zcvf db-crud-api-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz output/
    - name: Uploading assets
      uses: actions/upload-artifact@v3
      with:
        name: db-crud-api-${{ matrix.goos }}-${{ matrix.goarch }}
        path: db-crud-api-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
    - name: Application Version
      id: version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        change_path: "pkg/test"
    - name: release Version
      id: dbversion
      uses: paulhatch/semantic-version@v4.0.2
      with:
        major_pattern: "(MAJOR-DB)"
        minor_pattern: "(MINOR-DB)"
        change_path: "pkg/version"
        namespace: db

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          name/app
          ghcr.io/username/app
        # generate Docker tags based on the following events/attributes
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
